spring.application.name=BookStoreManagement


spring.datasource.url=jdbc:mysql://localhost:3306/bookpage?createDatabseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.data-driver-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true